### ISSUE TITLE
Boolean encodes too early, can't override tag

### ISSUE THREAD

**Issue by chrisridd** [wstrange/asn1lib#8]
This causes code like this (from the sorting control) to encode using the default tag, not the overridden one.

```
        var b = new ASN1Boolean(true); //todo: we should support tag override for asn1 bool
        b.tag = TYPE_REVERSE_ORDER; // override tag for CHOICE type
```

Taking out the _encode() from the constructor to align it with the other ASN1Objects will probably help.

**Comment by stevenroose** [comment]
Isn't a Boolean type required to have tag 1?
(https://msdn.microsoft.com/en-us/library/windows/desktop/bb648639(v=vs.85).aspx)

The _encode() is there because the encoded value of a boolean type is defined when it is instantiated. It seems like the tag is also hard coded into the _encode method instead of using the .tag getter.

**Comment by stevenroose** [comment]
But I don't think you should be allowed to change the tag of an ASN1Object on the fly. If you encode it once, and change the tag ofterwards, the encoded bytes will be cached and not updated.

So perhaps tag should be final or the encodedBytes var should be cleared when tag is changed.

**Comment by chrisridd** [comment]
Yes it is defined to be 1, but the tag definitely needs to be able to be overridden. ASN.1 is designed to do this using (typically) CONTEXT-SPECIFIC implicit tagging, e.g. from RFC 2891:

```
      SortKeyList ::= SEQUENCE OF SEQUENCE {
                 attributeType   AttributeDescription,
                 orderingRule    [0] MatchingRuleId OPTIONAL,
                 reverseOrder    [1] BOOLEAN DEFAULT FALSE }
```

I agree that changing it on the fly is not a reasonable thing to allow; but the caller must be able to create the object with the correct tagging, just like you can with ASN1Integer, ASN1Sequence, et al.

My lack of dart knowledge may be showing here, but I don't think that was the case before. Unless Warren's dartdap/lib/src/control/server_side_sort.dart was broken...

**Comment by wstrange** [comment]
So it looks like the library is somewhat brittle / inconsistent in that it allows the tag to wacked after object creation. To Steven's point - changing tags on the fly could lead to weird behaviour. 

Just changing the tag to final does not appear to work (Dart complains), but what could be done is to change it to a private var and have only a getter:

int _tag;
int get => _tag;

That would catch any attempts to set the tag.

Every constructor would then need to be changed to allow overriding the tag:

 ASN1Boolean(this._boolValue,{tag: BOOLEAN_TYPE}):super(tag:tag) {


Thoughts?

**Comment by chrisridd** [comment]
Yes, that constructor would work well. Protecting the tag from being changed afterwards sounds good too.

Should the ASN1Object constructor change to require the tag argument, and not default it to 0? That default is only useful AFAICR if you're building an end of contents object with indefinite length encoding. (LDAP doesn't use indefinite length encoding.) In every case you'll know the tag, and would never default it.

**Comment by stevenroose** [comment]
Consider this solution:
```dart
int _tag;
int get tag => _tag;
set tag(int tag) {
  _encodedBytes = null;
  return _tag = tag;
}

**Comment by wstrange** [comment]
Do we even need a setter for tag?

If we use the solution of passing the tag as a named param all the way up
to ASN1Object, this should suffice?

**Comment by stevenroose** [comment]
It does. But it will require every constructor to have the tag argument. 99% of the time, it will be ignored or even confuse users.

But that may indeed be the best solution. In that case tag can be made final I think.

**Comment by wstrange** [comment]
The setter for tag has been removed. Tag should only be set in an object constructor. I created a new 0.4.0 version because the public interface has changed. 

I went through the dartdap ldap library - and I think I found all the places where the tag was being set directly. 

Most users should be able to take the default tag argument:  EG
new ASN1Integer(x) ; // use the default tag for ASN1 Integer type 

So hopefully this will not be too confusing for library consumers. 

I tried declaring _tag final - but Dart complains. The constructors still need to be able to set this - and I could not figure out how to make it final. 

I will close this issue for now - but feel free to reopen if you think it needs improvement.
